#!/bin/bash
# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate Go models from UCP JSON Schemas

set -e

# Ensure we are in the script's directory
cd "$(dirname "$0")"

# Output directory
OUTPUT_DIR="models"

# Schema directory (relative to this script - assumes ucp repo is sibling)
SCHEMA_DIR="../ucp/spec"

# Check if schema directory exists
if [ ! -d "$SCHEMA_DIR" ]; then
    echo "Error: Schema directory not found at $SCHEMA_DIR"
    echo "Please ensure the UCP specification repository is available."
    echo ""
    echo "You can clone it with:"
    echo "  git clone https://github.com/Universal-Commerce-Protocol/ucp.git ../ucp"
    exit 1
fi

# Check if go-jsonschema is installed
if ! command -v go-jsonschema &> /dev/null; then
    echo "go-jsonschema not found. Installing..."
    go install github.com/atombender/go-jsonschema@latest
fi

echo "Generating Go models from $SCHEMA_DIR..."

# Create output directories
mkdir -p "$OUTPUT_DIR/discovery"
mkdir -p "$OUTPUT_DIR/schemas/shopping/types"
mkdir -p "$OUTPUT_DIR/services"
mkdir -p "$OUTPUT_DIR/handlers"

# File header for generated code
HEADER="// Code generated by go-jsonschema. DO NOT EDIT.
// Copyright 2026 UCP Authors
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"

# Generate discovery profile types
echo "Generating discovery types..."
go-jsonschema \
    --package discovery \
    --output "$OUTPUT_DIR/discovery/profile.go" \
    "$SCHEMA_DIR/discovery/profile_schema.json" 2>/dev/null || echo "Note: Some schemas may require manual handling"

# Generate core UCP types
echo "Generating core UCP types..."
go-jsonschema \
    --package schemas \
    --output "$OUTPUT_DIR/schemas/ucp.go" \
    "$SCHEMA_DIR/schemas/ucp.json" 2>/dev/null || echo "Note: Some schemas may require manual handling"

# Generate capability types
go-jsonschema \
    --package schemas \
    --output "$OUTPUT_DIR/schemas/capability.go" \
    "$SCHEMA_DIR/schemas/capability.json" 2>/dev/null || echo "Note: Some schemas may require manual handling"

# Generate shopping types
echo "Generating shopping types..."
for schema in "$SCHEMA_DIR"/schemas/shopping/*.json; do
    if [ -f "$schema" ]; then
        filename=$(basename "$schema" .json)
        # Convert filename to valid Go identifier
        gofile=$(echo "$filename" | sed 's/\./_/g' | sed 's/-/_/g')
        go-jsonschema \
            --package shopping \
            --output "$OUTPUT_DIR/schemas/shopping/${gofile}.go" \
            "$schema" 2>/dev/null || echo "Note: $filename may require manual handling"
    fi
done

# Generate shopping type definitions
echo "Generating shopping type definitions..."
for schema in "$SCHEMA_DIR"/schemas/shopping/types/*.json; do
    if [ -f "$schema" ]; then
        filename=$(basename "$schema" .json)
        # Convert filename to valid Go identifier
        gofile=$(echo "$filename" | sed 's/\./_/g' | sed 's/-/_/g')
        go-jsonschema \
            --package types \
            --output "$OUTPUT_DIR/schemas/shopping/types/${gofile}.go" \
            "$schema" 2>/dev/null || echo "Note: $filename may require manual handling"
    fi
done

# Generate service schema types
echo "Generating service types..."
go-jsonschema \
    --package services \
    --output "$OUTPUT_DIR/services/service.go" \
    "$SCHEMA_DIR/services/service_schema.json" 2>/dev/null || echo "Note: Some schemas may require manual handling"

echo ""
echo "Generation complete. Some schemas may need manual adjustments for:"
echo "  - oneOf/anyOf unions"
echo "  - allOf composition"
echo "  - Complex $ref resolution"
echo ""
echo "Check the models/ directory and run 'go build ./...' to verify."
